[request_definition]
r = sub, res, act, env

[policy_definition]
p = act, res, cond, eff

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = m_act(p.act, r.act) && m_res(p.res, r.res) && m_cond(p.cond, r.sub, r.res, r.env)
